#ifndef _PBD_COMPUTATION_GRAPH_H_
#define _PBD_COMPUTATION_GRAPH_H_

//global includes
#include <string>

/**
 * pbd_msgs namespace. ROS messages in this package are in that namespace by definition. Consequently helper code should be in it, too.
 *
 * @author Pascal Meissner
 * @version See SVN
 */
namespace pbd_msgs {

  /**
   * topics namespace. Contains definitions of string valued identifiers for ros topics used to transfer information between the ros nodes in the pbd toolchain.
   *
   * @author Pascal Meissner
   * @version See SVN
   */
  namespace Topics {
    
    //Topic for graphs generated by trivial_tracker containing raw trajectory data on scenes.
    const std::string SCENE_GRAPHS("/scene_graphs");

  }

}

#endif /* _PBD_COMPUTATION_GRAPH_H_ */
