#!/bin/bash

#Otherwise rosbag does not work.
source $HOME/.bashrc

#Make sure to write files directly on disk and not on nfs share.
cd /data/asr_recordings

#Record all markers and transformations
rosbag record -O ${1} /active_scene_recognition_ism/arrow_marker /active_scene_recognition_ism/arrow_marker_array /active_scene_recognition_ism/dome_meshes /active_scene_recognition_ism/dome_meshes_array /active_scene_recognition_ism/ism_marker /active_scene_recognition_ism/ism_marker_array /active_scene_recognition_ism/ptu_fov_marker /active_scene_recognition_ism/ptu_fov_marker_array /active_scene_recognition_ism/quadgrid_markers /active_scene_recognition_ism/samples2d_markers /active_scene_recognition_ism/samples2d_markers_array /active_scene_recognition_ism/samples3d_markers /active_scene_recognition_ism/samples3d_markers_array /active_scene_recognition_ism/tessellated_sphere_marker /active_scene_recognition_ism/tessellated_sphere_marker_array /stereo/objects /stereo/visualization_marker /stereo/visualization_marker_array /visualization_marker /visualization_marker_array /tf